const HERALDRY_CORPORATION_ID = 1000419;
const SHIP_EMBLEM_GROUP_ID = 4471;
const SLOT_GROUP_EMBLEM = 1;

const COSMETIC_TYPE_NONE = 0;
const COSMETIC_TYPE_CORPORATION_LOGO = 1;
const COSMETIC_TYPE_ALLIANCE_LOGO = 2;

const SHIP_LOGO_ENTITLEMENT_CORPORATION = 1;
const SHIP_LOGO_ENTITLEMENT_ALLIANCE = 2;

const COSMETIC_TYPE_BY_ENTITLEMENT_TYPE = Object.freeze({
  [SHIP_LOGO_ENTITLEMENT_CORPORATION]: COSMETIC_TYPE_CORPORATION_LOGO,
  [SHIP_LOGO_ENTITLEMENT_ALLIANCE]: COSMETIC_TYPE_ALLIANCE_LOGO,
});

const ENTITLEMENT_TYPE_BY_COSMETIC_TYPE = Object.freeze({
  [COSMETIC_TYPE_CORPORATION_LOGO]: SHIP_LOGO_ENTITLEMENT_CORPORATION,
  [COSMETIC_TYPE_ALLIANCE_LOGO]: SHIP_LOGO_ENTITLEMENT_ALLIANCE,
});

module.exports = {
  COSMETIC_TYPE_ALLIANCE_LOGO,
  COSMETIC_TYPE_BY_ENTITLEMENT_TYPE,
  COSMETIC_TYPE_CORPORATION_LOGO,
  COSMETIC_TYPE_NONE,
  ENTITLEMENT_TYPE_BY_COSMETIC_TYPE,
  HERALDRY_CORPORATION_ID,
  SHIP_EMBLEM_GROUP_ID,
  SHIP_LOGO_ENTITLEMENT_ALLIANCE,
  SHIP_LOGO_ENTITLEMENT_CORPORATION,
  SLOT_GROUP_EMBLEM,
};
