const BOOKMARKS_ADDED = "bookmarksAdded";
const BOOKMARKS_MOVED = "bookmarksMoved";
const BOOKMARKS_UPDATED = "bookmarksUpdated";
const BOOKMARKS_REMOVED = "bookmarksRemoved";
const FOLDER_UPDATED = "folderUpdated";
const SUBFOLDER_ADDED = "subfolderAdded";
const SUBFOLDER_UPDATED = "subfolderUpdated";
const SUBFOLDER_REMOVED = "subfolderRemoved";

const SHARED_BOOKMARK_DELAY_FILETIME = 1200000000n;
const MAX_BOOKMARKS_SENT_TO_CLIENT = 20000;
const MAX_BOOKMARK_NAME_LENGTH = 100;
const MAX_BOOKMARK_DESCRIPTION_LENGTH = 3900;
const MAX_FOLDER_NAME_LENGTH = 40;
const MAX_FOLDER_DESCRIPTION_LENGTH = 3900;
const MAX_BOOKMARKS_IN_SHARED_FOLDER = 500;
const MAX_BOOKMARKS_IN_PERSONAL_FOLDER = 3000;
const MAX_ACTIVE_SHARED_BOOKMARK_FOLDERS = 3;
const MAX_ACTIVE_PERSONAL_BOOKMARK_FOLDERS = 5;
const MAX_KNOWN_BOOKMARK_FOLDERS = 30;
const MAX_SUBFOLDERS = 30;

const ACCESS_NONE = 0;
const ACCESS_PERSONAL = 1;
const ACCESS_VIEW = 2;
const ACCESS_USE = 3;
const ACCESS_MANAGE = 4;
const ACCESS_ADMIN = 5;

const BOOKMARK_EXPIRY_NONE = 0;
const BOOKMARK_EXPIRY_4HOURS = 1;
const BOOKMARK_EXPIRY_2DAYS = 2;
const BOOKMARK_EXPIRY_24HOURS = 3;

const TYPE_SOLAR_SYSTEM = 5;
const OWNER_SYSTEM = 1;

module.exports = {
  ACCESS_ADMIN,
  ACCESS_MANAGE,
  ACCESS_NONE,
  ACCESS_PERSONAL,
  ACCESS_USE,
  ACCESS_VIEW,
  BOOKMARKS_ADDED,
  BOOKMARKS_MOVED,
  BOOKMARKS_REMOVED,
  BOOKMARKS_UPDATED,
  BOOKMARK_EXPIRY_24HOURS,
  BOOKMARK_EXPIRY_2DAYS,
  BOOKMARK_EXPIRY_4HOURS,
  BOOKMARK_EXPIRY_NONE,
  FOLDER_UPDATED,
  MAX_ACTIVE_PERSONAL_BOOKMARK_FOLDERS,
  MAX_ACTIVE_SHARED_BOOKMARK_FOLDERS,
  MAX_BOOKMARKS_IN_PERSONAL_FOLDER,
  MAX_BOOKMARKS_IN_SHARED_FOLDER,
  MAX_BOOKMARKS_SENT_TO_CLIENT,
  MAX_BOOKMARK_DESCRIPTION_LENGTH,
  MAX_BOOKMARK_NAME_LENGTH,
  MAX_FOLDER_DESCRIPTION_LENGTH,
  MAX_FOLDER_NAME_LENGTH,
  MAX_KNOWN_BOOKMARK_FOLDERS,
  MAX_SUBFOLDERS,
  OWNER_SYSTEM,
  SHARED_BOOKMARK_DELAY_FILETIME,
  SUBFOLDER_ADDED,
  SUBFOLDER_REMOVED,
  SUBFOLDER_UPDATED,
  TYPE_SOLAR_SYSTEM,
};
