const STRUCTURE_STATE = Object.freeze({
  UNKNOWN: 0,
  UNANCHORED: 1,
  ANCHORING: 2,
  ONLINE_DEPRECATED: 100,
  FITTING_INVULNERABLE: 101,
  ONLINING_VULNERABLE: 102,
  SHIELD_VULNERABLE: 110,
  ARMOR_REINFORCE: 111,
  ARMOR_VULNERABLE: 112,
  HULL_REINFORCE: 113,
  HULL_VULNERABLE: 114,
  ANCHOR_VULNERABLE: 115,
  DEPLOY_VULNERABLE: 116,
  FOB_INVULNERABLE: 118,
});

const STRUCTURE_STATE_NAME_BY_ID = Object.freeze({
  [STRUCTURE_STATE.UNKNOWN]: "unknown",
  [STRUCTURE_STATE.UNANCHORED]: "unanchored",
  [STRUCTURE_STATE.ANCHORING]: "anchoring",
  [STRUCTURE_STATE.ONLINE_DEPRECATED]: "online_deprecated",
  [STRUCTURE_STATE.FITTING_INVULNERABLE]: "fitting_invulnerable",
  [STRUCTURE_STATE.ONLINING_VULNERABLE]: "onlining_vulnerable",
  [STRUCTURE_STATE.SHIELD_VULNERABLE]: "shield_vulnerable",
  [STRUCTURE_STATE.ARMOR_REINFORCE]: "armor_reinforce",
  [STRUCTURE_STATE.ARMOR_VULNERABLE]: "armor_vulnerable",
  [STRUCTURE_STATE.HULL_REINFORCE]: "hull_reinforce",
  [STRUCTURE_STATE.HULL_VULNERABLE]: "hull_vulnerable",
  [STRUCTURE_STATE.ANCHOR_VULNERABLE]: "anchor_vulnerable",
  [STRUCTURE_STATE.DEPLOY_VULNERABLE]: "deploy_vulnerable",
  [STRUCTURE_STATE.FOB_INVULNERABLE]: "fob_invulnerable",
});

const STRUCTURE_STATE_ID_BY_NAME = Object.freeze(
  Object.fromEntries(
    Object.entries(STRUCTURE_STATE_NAME_BY_ID).map(([stateID, stateName]) => [
      stateName,
      Number(stateID),
    ]),
  ),
);

const STRUCTURE_DISABLED_STATES = new Set([
  STRUCTURE_STATE.UNKNOWN,
  STRUCTURE_STATE.UNANCHORED,
  STRUCTURE_STATE.ANCHORING,
  STRUCTURE_STATE.HULL_REINFORCE,
  STRUCTURE_STATE.HULL_VULNERABLE,
  STRUCTURE_STATE.ANCHOR_VULNERABLE,
  STRUCTURE_STATE.ONLINING_VULNERABLE,
  STRUCTURE_STATE.DEPLOY_VULNERABLE,
]);

const STRUCTURE_OFFLINE_STATES = new Set([
  STRUCTURE_STATE.UNKNOWN,
  STRUCTURE_STATE.UNANCHORED,
  STRUCTURE_STATE.ANCHORING,
  STRUCTURE_STATE.ANCHOR_VULNERABLE,
  STRUCTURE_STATE.DEPLOY_VULNERABLE,
]);

const STRUCTURE_TETHER_ENABLED_STATES = new Set([
  STRUCTURE_STATE.ONLINING_VULNERABLE,
  STRUCTURE_STATE.SHIELD_VULNERABLE,
  STRUCTURE_STATE.ARMOR_REINFORCE,
  STRUCTURE_STATE.ARMOR_VULNERABLE,
  STRUCTURE_STATE.HULL_REINFORCE,
  STRUCTURE_STATE.HULL_VULNERABLE,
  STRUCTURE_STATE.FOB_INVULNERABLE,
]);

const STRUCTURE_VULNERABLE_STATES = new Set([
  STRUCTURE_STATE.ONLINING_VULNERABLE,
  STRUCTURE_STATE.SHIELD_VULNERABLE,
  STRUCTURE_STATE.ARMOR_VULNERABLE,
  STRUCTURE_STATE.HULL_VULNERABLE,
  STRUCTURE_STATE.ANCHOR_VULNERABLE,
  STRUCTURE_STATE.DEPLOY_VULNERABLE,
]);

const STRUCTURE_UPKEEP_STATE = Object.freeze({
  FULL_POWER: 1,
  LOW_POWER: 2,
  ABANDONED: 3,
});

const STRUCTURE_UPKEEP_NAME_BY_ID = Object.freeze({
  [STRUCTURE_UPKEEP_STATE.FULL_POWER]: "full_power",
  [STRUCTURE_UPKEEP_STATE.LOW_POWER]: "low_power",
  [STRUCTURE_UPKEEP_STATE.ABANDONED]: "abandoned",
});

const STRUCTURE_UPKEEP_ID_BY_NAME = Object.freeze(
  Object.fromEntries(
    Object.entries(STRUCTURE_UPKEEP_NAME_BY_ID).map(([stateID, stateName]) => [
      stateName,
      Number(stateID),
    ]),
  ),
);

const STRUCTURE_SERVICE_ID = Object.freeze({
  DOCKING: 1,
  FITTING: 2,
  OFFICES: 3,
  REPROCESSING: 4,
  MARKET: 5,
  MEDICAL: 6,
  MISSION: 7,
  REPAIR: 8,
  INSURANCE: 9,
  JUMP_CLONE: 10,
  LOYALTY_STORE: 11,
  FACTION_WARFARE: 12,
  SECURITY_OFFICE: 13,
  MOON_MINING: 14,
  JUMP_BRIDGE: 15,
  CYNO_BEACON: 16,
  CYNO_JAMMER: 17,
  AUTOMOONMINING: 18,
  INDUSTRY: 20,
  MANUFACTURING: 21,
  MANUFACTURING_BASIC: 22,
  MANUFACTURING_CAPITAL: 23,
  MANUFACTURING_SUPERCAPITAL: 24,
  LABORATORY: 30,
  LABORATORY_RESEARCH_TIME: 31,
  LABORATORY_RESEARCH_MATERIAL: 32,
  LABORATORY_COPYING: 33,
  LABORATORY_INVENTION: 34,
  REACTIONS: 40,
  REACTIONS_COMPOSITE: 41,
  REACTIONS_BIOCHEMICAL: 42,
  REACTIONS_HYBRID: 43,
});

const STRUCTURE_SERVICE_STATE = Object.freeze({
  ONLINE: 1,
  OFFLINE: 2,
  CLEANUP: 3,
});

const STRUCTURE_SERVICE_NAME_BY_ID = Object.freeze(
  Object.fromEntries(
    Object.entries(STRUCTURE_SERVICE_ID).map(([name, serviceID]) => [
      serviceID,
      name.toLowerCase(),
    ]),
  ),
);

const STRUCTURE_SIZE = Object.freeze({
  FLEX: "STRUCTURE_SIZE_FLEX",
  MEDIUM: "STRUCTURE_SIZE_MEDIUM",
  LARGE: "STRUCTURE_SIZE_LARGE",
  EXTRA_LARGE: "STRUCTURE_SIZE_EXTRA_LARGE",
  UNDEFINED: "STRUCTURE_SIZE_UNDEFINED",
});

const STRUCTURE_FAMILY = Object.freeze({
  CITADEL: "citadel",
  ENGINEERING: "engineering",
  REFINERY: "refinery",
  FLEX: "flex",
  OBSERVATORY: "observatory",
  SOV: "sov",
  STRONGHOLD: "stronghold",
  UNKNOWN: "unknown",
});

const STRUCTURE_GROUP_ID = Object.freeze({
  ENGINEERING_COMPLEX: 1404,
  LABORATORY: 1405,
  REFINERY: 1406,
  OBSERVATORY: 1407,
  JUMP_GATE: 1408,
  ADMINISTRATION_HUB: 1409,
  ADVERTISEMENT: 1410,
  CITADEL: 1657,
  UPWELL_MONUMENT: 2015,
  CYNO_JAMMER: 2016,
  CYNO_BEACON: 2017,
  PIRATE_STRONGHOLD: 1924,
  FOB: 4644,
  METENOX: 4744,
});

const STRUCTURE_TIMER_SECONDS = Object.freeze({
  REPAIR_DEFAULT: 900,
  REPAIR_HULL: 1800,
  ANCHORING: 86400,
  UNANCHORING: 604800,
  FLEX_UNANCHORING: 2700,
  METENOX_UNANCHORING: 259200,
  FITTING_INVULNERABLE: 300,
  ARMOR_REINFORCE_DEFAULT: 86400,
  ARMOR_REINFORCE_NULL_LOW: 302400,
  ARMOR_REINFORCE_HIGH: 388800,
  HULL_REINFORCE_DEFAULT: 129600,
  HULL_REINFORCE_NULL_LOW: 216000,
  HULL_REINFORCE_HIGH: 388800,
});

const STRUCTURE_REPAIR_SECONDS_BY_STATE = Object.freeze({
  [STRUCTURE_STATE.ANCHOR_VULNERABLE]: 900,
  [STRUCTURE_STATE.ONLINING_VULNERABLE]: 900,
  [STRUCTURE_STATE.SHIELD_VULNERABLE]: 900,
  [STRUCTURE_STATE.ARMOR_VULNERABLE]: 900,
  [STRUCTURE_STATE.HULL_VULNERABLE]: 1800,
  [STRUCTURE_STATE.DEPLOY_VULNERABLE]: 900,
});

const STRUCTURE_UNANCHOR_CANCEL_STATES = new Set([
  STRUCTURE_STATE.UNKNOWN,
  STRUCTURE_STATE.UNANCHORED,
  STRUCTURE_STATE.ANCHORING,
  STRUCTURE_STATE.FITTING_INVULNERABLE,
  STRUCTURE_STATE.ARMOR_REINFORCE,
  STRUCTURE_STATE.ARMOR_VULNERABLE,
  STRUCTURE_STATE.HULL_REINFORCE,
  STRUCTURE_STATE.HULL_VULNERABLE,
  STRUCTURE_STATE.ANCHOR_VULNERABLE,
  STRUCTURE_STATE.DEPLOY_VULNERABLE,
]);

const DEFAULT_REINFORCE_WEEKDAY = 5;
const DEFAULT_REINFORCE_HOUR = 18;
const NO_REINFORCEMENT_WEEKDAY = 255;
const DEFAULT_STRUCTURE_RADIUS = 10000;
const DEFAULT_STRUCTURE_TETHER_RANGE = 10000;
const DEFAULT_STRUCTURE_DOCKING_RADIUS = 2500;
const NEXT_STRUCTURE_ID_START = 1030000000000;
const NEXT_ASSET_WRAP_ID_START = 1040000000000;

const STRUCTURE_TYPE_PRESETS = Object.freeze({
  32226: {
    typeID: 32226,
    family: STRUCTURE_FAMILY.SOV,
    size: STRUCTURE_SIZE.FLEX,
  },
  32458: {
    typeID: 32458,
    family: STRUCTURE_FAMILY.SOV,
    size: STRUCTURE_SIZE.LARGE,
  },
  46363: {
    typeID: 46363,
    family: STRUCTURE_FAMILY.STRONGHOLD,
    size: STRUCTURE_SIZE.LARGE,
    dockable: false,
    defaultQuantumCoreTypeID: null,
  },
  46364: {
    typeID: 46364,
    family: STRUCTURE_FAMILY.STRONGHOLD,
    size: STRUCTURE_SIZE.LARGE,
    dockable: false,
    defaultQuantumCoreTypeID: null,
  },
  78260: {
    typeID: 78260,
    family: STRUCTURE_FAMILY.STRONGHOLD,
    size: STRUCTURE_SIZE.LARGE,
    dockable: false,
    defaultQuantumCoreTypeID: null,
  },
  79172: {
    typeID: 79172,
    family: STRUCTURE_FAMILY.STRONGHOLD,
    size: STRUCTURE_SIZE.LARGE,
    dockable: false,
    defaultQuantumCoreTypeID: null,
  },
  81080: {
    typeID: 81080,
    family: STRUCTURE_FAMILY.SOV,
    size: STRUCTURE_SIZE.FLEX,
    dockable: false,
    defaultQuantumCoreTypeID: null,
  },
  84294: {
    typeID: 84294,
    family: STRUCTURE_FAMILY.STRONGHOLD,
    size: STRUCTURE_SIZE.LARGE,
    dockable: false,
    defaultQuantumCoreTypeID: null,
  },
  85230: {
    typeID: 85230,
    family: STRUCTURE_FAMILY.SOV,
    size: STRUCTURE_SIZE.FLEX,
    dockable: false,
    defaultQuantumCoreTypeID: null,
  },
  85980: {
    typeID: 85980,
    family: STRUCTURE_FAMILY.SOV,
    size: STRUCTURE_SIZE.FLEX,
    dockable: false,
    defaultQuantumCoreTypeID: null,
  },
  87227: {
    typeID: 87227,
    family: STRUCTURE_FAMILY.STRONGHOLD,
    size: STRUCTURE_SIZE.LARGE,
    dockable: false,
    defaultQuantumCoreTypeID: null,
  },
  35825: {
    typeID: 35825,
    family: STRUCTURE_FAMILY.ENGINEERING,
    size: STRUCTURE_SIZE.MEDIUM,
    defaultQuantumCoreTypeID: 56203,
  },
  35826: {
    typeID: 35826,
    family: STRUCTURE_FAMILY.ENGINEERING,
    size: STRUCTURE_SIZE.LARGE,
    defaultQuantumCoreTypeID: 56206,
  },
  35827: {
    typeID: 35827,
    family: STRUCTURE_FAMILY.ENGINEERING,
    size: STRUCTURE_SIZE.EXTRA_LARGE,
    defaultQuantumCoreTypeID: 56208,
  },
  35832: {
    typeID: 35832,
    family: STRUCTURE_FAMILY.CITADEL,
    size: STRUCTURE_SIZE.MEDIUM,
    defaultQuantumCoreTypeID: 56201,
  },
  35833: {
    typeID: 35833,
    family: STRUCTURE_FAMILY.CITADEL,
    size: STRUCTURE_SIZE.LARGE,
    defaultQuantumCoreTypeID: 56204,
  },
  35834: {
    typeID: 35834,
    family: STRUCTURE_FAMILY.CITADEL,
    size: STRUCTURE_SIZE.EXTRA_LARGE,
    defaultQuantumCoreTypeID: 56207,
  },
  35835: {
    typeID: 35835,
    family: STRUCTURE_FAMILY.REFINERY,
    size: STRUCTURE_SIZE.MEDIUM,
    defaultQuantumCoreTypeID: 56202,
  },
  35836: {
    typeID: 35836,
    family: STRUCTURE_FAMILY.REFINERY,
    size: STRUCTURE_SIZE.LARGE,
    defaultQuantumCoreTypeID: 56205,
  },
  35840: {
    typeID: 35840,
    family: STRUCTURE_FAMILY.FLEX,
    size: STRUCTURE_SIZE.FLEX,
    defaultQuantumCoreTypeID: null,
  },
  35841: {
    typeID: 35841,
    family: STRUCTURE_FAMILY.FLEX,
    size: STRUCTURE_SIZE.FLEX,
    defaultQuantumCoreTypeID: null,
  },
  37534: {
    typeID: 37534,
    family: STRUCTURE_FAMILY.FLEX,
    size: STRUCTURE_SIZE.FLEX,
    defaultQuantumCoreTypeID: null,
  },
  40340: {
    typeID: 40340,
    family: STRUCTURE_FAMILY.CITADEL,
    size: STRUCTURE_SIZE.EXTRA_LARGE,
    defaultQuantumCoreTypeID: 56207,
  },
  47512: {
    typeID: 47512,
    family: STRUCTURE_FAMILY.CITADEL,
    size: STRUCTURE_SIZE.LARGE,
    defaultQuantumCoreTypeID: 56204,
  },
  47513: {
    typeID: 47513,
    family: STRUCTURE_FAMILY.CITADEL,
    size: STRUCTURE_SIZE.LARGE,
    defaultQuantumCoreTypeID: 56204,
  },
  47514: {
    typeID: 47514,
    family: STRUCTURE_FAMILY.CITADEL,
    size: STRUCTURE_SIZE.LARGE,
    defaultQuantumCoreTypeID: 56204,
  },
  47515: {
    typeID: 47515,
    family: STRUCTURE_FAMILY.CITADEL,
    size: STRUCTURE_SIZE.LARGE,
    defaultQuantumCoreTypeID: 56204,
  },
  47516: {
    typeID: 47516,
    family: STRUCTURE_FAMILY.CITADEL,
    size: STRUCTURE_SIZE.LARGE,
    defaultQuantumCoreTypeID: 56204,
  },
  81826: {
    typeID: 81826,
    family: STRUCTURE_FAMILY.REFINERY,
    size: STRUCTURE_SIZE.MEDIUM,
    dockable: false,
    defaultQuantumCoreTypeID: null,
  },
});

const ENGINEERING_SERVICE_IDS = Object.freeze([
  STRUCTURE_SERVICE_ID.DOCKING,
  STRUCTURE_SERVICE_ID.FITTING,
  STRUCTURE_SERVICE_ID.OFFICES,
  STRUCTURE_SERVICE_ID.MEDICAL,
  STRUCTURE_SERVICE_ID.REPAIR,
  STRUCTURE_SERVICE_ID.INSURANCE,
  STRUCTURE_SERVICE_ID.INDUSTRY,
  STRUCTURE_SERVICE_ID.MANUFACTURING,
  STRUCTURE_SERVICE_ID.MANUFACTURING_BASIC,
  STRUCTURE_SERVICE_ID.MANUFACTURING_CAPITAL,
  STRUCTURE_SERVICE_ID.MANUFACTURING_SUPERCAPITAL,
  STRUCTURE_SERVICE_ID.LABORATORY,
  STRUCTURE_SERVICE_ID.LABORATORY_RESEARCH_TIME,
  STRUCTURE_SERVICE_ID.LABORATORY_RESEARCH_MATERIAL,
  STRUCTURE_SERVICE_ID.LABORATORY_COPYING,
  STRUCTURE_SERVICE_ID.LABORATORY_INVENTION,
]);

const CITADEL_SERVICE_IDS = Object.freeze([
  STRUCTURE_SERVICE_ID.DOCKING,
  STRUCTURE_SERVICE_ID.FITTING,
  STRUCTURE_SERVICE_ID.OFFICES,
  STRUCTURE_SERVICE_ID.REPROCESSING,
  STRUCTURE_SERVICE_ID.MARKET,
  STRUCTURE_SERVICE_ID.MEDICAL,
  STRUCTURE_SERVICE_ID.REPAIR,
  STRUCTURE_SERVICE_ID.INSURANCE,
  STRUCTURE_SERVICE_ID.JUMP_CLONE,
  STRUCTURE_SERVICE_ID.LOYALTY_STORE,
]);

const REFINERY_SERVICE_IDS = Object.freeze([
  STRUCTURE_SERVICE_ID.DOCKING,
  STRUCTURE_SERVICE_ID.FITTING,
  STRUCTURE_SERVICE_ID.OFFICES,
  STRUCTURE_SERVICE_ID.MEDICAL,
  STRUCTURE_SERVICE_ID.REPROCESSING,
  STRUCTURE_SERVICE_ID.REPAIR,
  STRUCTURE_SERVICE_ID.INSURANCE,
  STRUCTURE_SERVICE_ID.MOON_MINING,
  STRUCTURE_SERVICE_ID.AUTOMOONMINING,
  STRUCTURE_SERVICE_ID.REACTIONS,
  STRUCTURE_SERVICE_ID.REACTIONS_COMPOSITE,
  STRUCTURE_SERVICE_ID.REACTIONS_BIOCHEMICAL,
  STRUCTURE_SERVICE_ID.REACTIONS_HYBRID,
]);

const FLEX_SERVICE_IDS_BY_TYPE_ID = Object.freeze({
  35840: [STRUCTURE_SERVICE_ID.CYNO_BEACON],
  35841: [STRUCTURE_SERVICE_ID.JUMP_BRIDGE],
  37534: [STRUCTURE_SERVICE_ID.CYNO_JAMMER],
});

const TATARA_EXCLUDED_DOCK_GROUP_NAMES = Object.freeze([
  "carrier",
  "force auxiliary",
  "dreadnought",
  "lancer dreadnought",
]);

const ONE_WAY_UNDOCK_TYPE_IDS = Object.freeze({
  35825: ["capital", "supercapital"],
  35826: ["capital", "supercapital"],
  35827: ["supercapital"],
});

function getAllowedServicesForStructureType(typeID, family = null) {
  const resolvedTypeID = Number(typeID) || 0;
  if (FLEX_SERVICE_IDS_BY_TYPE_ID[resolvedTypeID]) {
    return [...FLEX_SERVICE_IDS_BY_TYPE_ID[resolvedTypeID]];
  }

  const preset = STRUCTURE_TYPE_PRESETS[resolvedTypeID] || null;
  const resolvedFamily = family || (preset && preset.family) || STRUCTURE_FAMILY.UNKNOWN;
  if (resolvedFamily === STRUCTURE_FAMILY.CITADEL) {
    return [...CITADEL_SERVICE_IDS];
  }
  if (resolvedFamily === STRUCTURE_FAMILY.ENGINEERING) {
    return [...ENGINEERING_SERVICE_IDS];
  }
  if (resolvedFamily === STRUCTURE_FAMILY.REFINERY) {
    return [...REFINERY_SERVICE_IDS];
  }
  if (resolvedFamily === STRUCTURE_FAMILY.FLEX) {
    return [...(FLEX_SERVICE_IDS_BY_TYPE_ID[resolvedTypeID] || [])];
  }
  if (resolvedFamily === STRUCTURE_FAMILY.SOV) {
    return [];
  }
  if (resolvedFamily === STRUCTURE_FAMILY.STRONGHOLD) {
    return [];
  }
  return [
    STRUCTURE_SERVICE_ID.DOCKING,
    STRUCTURE_SERVICE_ID.FITTING,
  ];
}

module.exports = {
  STRUCTURE_STATE,
  STRUCTURE_STATE_NAME_BY_ID,
  STRUCTURE_STATE_ID_BY_NAME,
  STRUCTURE_DISABLED_STATES,
  STRUCTURE_OFFLINE_STATES,
  STRUCTURE_TETHER_ENABLED_STATES,
  STRUCTURE_VULNERABLE_STATES,
  STRUCTURE_UPKEEP_STATE,
  STRUCTURE_UPKEEP_NAME_BY_ID,
  STRUCTURE_UPKEEP_ID_BY_NAME,
  STRUCTURE_SERVICE_ID,
  STRUCTURE_SERVICE_STATE,
  STRUCTURE_SERVICE_NAME_BY_ID,
  STRUCTURE_SIZE,
  STRUCTURE_FAMILY,
  STRUCTURE_GROUP_ID,
  STRUCTURE_TIMER_SECONDS,
  STRUCTURE_UNANCHOR_CANCEL_STATES,
  STRUCTURE_REPAIR_SECONDS_BY_STATE,
  DEFAULT_REINFORCE_WEEKDAY,
  DEFAULT_REINFORCE_HOUR,
  NO_REINFORCEMENT_WEEKDAY,
  DEFAULT_STRUCTURE_RADIUS,
  DEFAULT_STRUCTURE_TETHER_RANGE,
  DEFAULT_STRUCTURE_DOCKING_RADIUS,
  NEXT_STRUCTURE_ID_START,
  NEXT_ASSET_WRAP_ID_START,
  STRUCTURE_TYPE_PRESETS,
  TATARA_EXCLUDED_DOCK_GROUP_NAMES,
  ONE_WAY_UNDOCK_TYPE_IDS,
  getAllowedServicesForStructureType,
};
