const REPROCESSING_STATIC_TABLE = "reprocessingStatic";
const REPROCESSING_FACILITY_STATE_TABLE = "reprocessingFacilityState";
const REPROCESSING_CLIENT_RANDOMIZED_TABLE = "reprocessingClientRandomizedMaterials";

const TYPE_REPROCESSING = 3385;
const TYPE_REPROCESSING_EFFICIENCY = 3389;
const TYPE_SCRAPMETAL_PROCESSING = 12196;
const TYPE_GAS_DECOMPRESSION_EFFICIENCY = 62452;

const CATEGORY_HARVESTABLE_CLOUD = 2;
const CATEGORY_ASTEROID = 25;

const ATTRIBUTE_REPROCESSING_SKILL_TYPE = 790;
const ATTRIBUTE_REFINING_YIELD_MUTATOR = "refiningYieldMutator";
const ATTRIBUTE_GAS_DECOMPRESSION_EFFICIENCY_BONUS = "gasDecompressionEfficiencyBonus";

const ATTRIBUTE_STRUCTURE_RIG_SIZE = 1547;
const ATTRIBUTE_RIG_SECURITY_MODIFIER_HIGH = 2355;
const ATTRIBUTE_RIG_SECURITY_MODIFIER_LOW = 2356;
const ATTRIBUTE_RIG_SECURITY_MODIFIER_NULL = 2357;
const ATTRIBUTE_RIG_REFINING_YIELD_MULTIPLIER = 717;
const ATTRIBUTE_STRUCTURE_REPROCESSING_YIELD_BONUS_PERCENT = 2722;
const ATTRIBUTE_STRUCTURE_GAS_DECOMPRESSION_EFFICIENCY_BASE = 3262;
const ATTRIBUTE_STRUCTURE_GAS_DECOMPRESSION_EFFICIENCY_BONUS_ADD = 3261;

const EFFECT_STRUCTURE_REPROCESSING_RIG_SECURITY_MODIFICATION = 6673;
const EFFECT_STRUCTURE_RIG_ASTEROID_ORE_YIELD = 6674;
const EFFECT_STRUCTURE_RIG_MOON_ORE_YIELD = 6675;
const EFFECT_STRUCTURE_RIG_ICE_YIELD = 6678;
const EFFECT_REFINERY_REPROCESSING_YIELD_BONUS = 6989;
const EFFECT_REFINERY_GAS_DECOMPRESSION_EFFICIENCY_BONUS = 8369;

const DEFAULT_STATION_REPROCESSING_EFFICIENCY = 0.5;
const DEFAULT_STATION_REPROCESSING_TAX = 0.05;
const NPC_STANDING_TAX_ZERO_POINT = 6.67;

const STRUCTURE_DEFAULT_REPROCESSING_EFFICIENCY = 0.5;
const STRUCTURE_DEFAULT_GAS_DECOMPRESSION_EFFICIENCY = 0.8;

const DEFAULT_IN_SPACE_COMPRESSION_RANGE_METERS = 250_000;

module.exports = {
  ATTRIBUTE_RIG_REFINING_YIELD_MULTIPLIER,
  ATTRIBUTE_RIG_SECURITY_MODIFIER_HIGH,
  ATTRIBUTE_RIG_SECURITY_MODIFIER_LOW,
  ATTRIBUTE_RIG_SECURITY_MODIFIER_NULL,
  ATTRIBUTE_GAS_DECOMPRESSION_EFFICIENCY_BONUS,
  ATTRIBUTE_REFINING_YIELD_MUTATOR,
  ATTRIBUTE_REPROCESSING_SKILL_TYPE,
  ATTRIBUTE_STRUCTURE_GAS_DECOMPRESSION_EFFICIENCY_BASE,
  ATTRIBUTE_STRUCTURE_GAS_DECOMPRESSION_EFFICIENCY_BONUS_ADD,
  ATTRIBUTE_STRUCTURE_REPROCESSING_YIELD_BONUS_PERCENT,
  ATTRIBUTE_STRUCTURE_RIG_SIZE,
  CATEGORY_ASTEROID,
  CATEGORY_HARVESTABLE_CLOUD,
  DEFAULT_IN_SPACE_COMPRESSION_RANGE_METERS,
  DEFAULT_STATION_REPROCESSING_EFFICIENCY,
  DEFAULT_STATION_REPROCESSING_TAX,
  EFFECT_REFINERY_GAS_DECOMPRESSION_EFFICIENCY_BONUS,
  EFFECT_REFINERY_REPROCESSING_YIELD_BONUS,
  EFFECT_STRUCTURE_REPROCESSING_RIG_SECURITY_MODIFICATION,
  EFFECT_STRUCTURE_RIG_ASTEROID_ORE_YIELD,
  EFFECT_STRUCTURE_RIG_ICE_YIELD,
  EFFECT_STRUCTURE_RIG_MOON_ORE_YIELD,
  NPC_STANDING_TAX_ZERO_POINT,
  REPROCESSING_CLIENT_RANDOMIZED_TABLE,
  REPROCESSING_FACILITY_STATE_TABLE,
  REPROCESSING_STATIC_TABLE,
  STRUCTURE_DEFAULT_GAS_DECOMPRESSION_EFFICIENCY,
  STRUCTURE_DEFAULT_REPROCESSING_EFFICIENCY,
  TYPE_GAS_DECOMPRESSION_EFFICIENCY,
  TYPE_REPROCESSING,
  TYPE_REPROCESSING_EFFICIENCY,
  TYPE_SCRAPMETAL_PROCESSING,
};
