const SOVEREIGNTY_TABLE = "sovereignty";

const TYPE_TERRITORIAL_CLAIM_UNIT = 32226;
const TYPE_INFRASTRUCTURE_HUB = 32458;
const TYPE_MERCENARY_DEN = 85230;
const TYPE_SENESCHAL_MERCENARY_DEN = 85980;

const ATTRIBUTE_DEV_INDEX_MILITARY = 1583;
const ATTRIBUTE_DEV_INDEX_INDUSTRIAL = 1584;
const ATTRIBUTE_DEV_INDEX_SOVEREIGNTY = 1615;

const CLAIM_DAYS_TO_SECONDS = 86400;
const PRIME_TIME_CHANGE_DELAY_MS = 48 * 60 * 60 * 1000;
const CAPITAL_SYSTEM_CHANGE_DELAY_MS = 7 * 24 * 60 * 60 * 1000;
const VULNERABILITY_WINDOW_BASE_HOURS = 18;
const FILETIME_EPOCH_OFFSET = 116444736000000000n;
const FILETIME_TICKS_PER_MILLISECOND = 10000n;
const STRUCTURE_SCORE_UPDATED = 0;
const STRUCTURES_UPDATED = 1;
const ALLOWED_DURATION_AFTER_SOVHUB_CLAIM_SECONDS = 86400;
const MERCENARY_DEN_MANAGEMENT_SKILL_TYPE_ID = 85233;
const DEFAULT_MERCENARY_DEN_ACTIVITY_CAPACITY = 3;
const DEFAULT_MERCENARY_DEN_ABSOLUTE_MAXIMUM = 5;

module.exports = {
  SOVEREIGNTY_TABLE,
  TYPE_TERRITORIAL_CLAIM_UNIT,
  TYPE_INFRASTRUCTURE_HUB,
  TYPE_MERCENARY_DEN,
  TYPE_SENESCHAL_MERCENARY_DEN,
  ATTRIBUTE_DEV_INDEX_MILITARY,
  ATTRIBUTE_DEV_INDEX_INDUSTRIAL,
  ATTRIBUTE_DEV_INDEX_SOVEREIGNTY,
  CLAIM_DAYS_TO_SECONDS,
  PRIME_TIME_CHANGE_DELAY_MS,
  CAPITAL_SYSTEM_CHANGE_DELAY_MS,
  VULNERABILITY_WINDOW_BASE_HOURS,
  FILETIME_EPOCH_OFFSET,
  FILETIME_TICKS_PER_MILLISECOND,
  STRUCTURE_SCORE_UPDATED,
  STRUCTURES_UPDATED,
  ALLOWED_DURATION_AFTER_SOVHUB_CLAIM_SECONDS,
  MERCENARY_DEN_MANAGEMENT_SKILL_TYPE_ID,
  DEFAULT_MERCENARY_DEN_ACTIVITY_CAPACITY,
  DEFAULT_MERCENARY_DEN_ABSOLUTE_MAXIMUM,
};
