const FILETIME_TICKS_PER_MS = 10000n;
const SEED_DURATION_MS = 3 * 24 * 60 * 60 * 1000;
const HISTORY_PAGE_SIZE = 50;
const DEFAULT_GRAB_SIZE = 256;
const DEFAULT_STARTUP_SEED_COUNT = 3;
const MAX_QA_SEED_COUNT = 1000;

const SEED_OWNER_ID = 140000004;
const SEED_ID_BASE = 980000000;
const SEED_FALLBACK_STATION_ID = 60003760;
const SEED_FALLBACK_SYSTEM_ID = 30000142;
const SEED_FALLBACK_TYPE_ID = 9854;
const SEED_TICKET_COUNTS = Object.freeze([8, 16]);
const SEED_TICKET_PRICES = Object.freeze([1_000, 2_500, 5_000]);

const SEED_PREFERRED_TYPE_IDS = Object.freeze([
  9854, // Polaris Inspector Frigate
  9862, // Polaris Centurion Frigate
  9860, // Polaris Legatus Frigate
  1233, // Polaris Enigma Frigate
  9858, // Polaris Centurion TEST
]);
const SEED_FALLBACK_ITEM_TYPE_IDS = Object.freeze([
  40340, // Upwell Palatine Keepstar
  40519, // Skill Extractor
  2420, // Torpedo Launcher II
  41239, // 10000MN Afterburner II
  12068, // 100MN Afterburner II
]);

const TOKEN_TYPE_ID = 52568;
const BROKERS_FEE = 0.05;
const RAFFLE_TAX_PERCENTAGE = 0.05;
const DEFAULT_PLEX_PRICE_OVERRIDE = 3_500_000;
const TOKEN_PRICE_DIVISOR = 10;
const MIN_TOTAL_PRICE = 1_000;
const MAX_TOTAL_PRICE = 10_000_000_000_000;
const TICKET_COUNT_POOL = Object.freeze([8, 16, 48, 512]);
const PRIVATE_RESTRICTION_ID = 1;
const RAFFLE_ESCROW_FLAG = 178;
const SEEDED_TOKEN_STACK_SIZE = 64;
const BLUEPRINT_TYPE = Object.freeze({
  ALL: 0,
  ORIGINAL: 1,
  COPY: 2,
});
const ALLOWED_CATEGORY_IDS = Object.freeze([
  9, // Blueprint
  91, // Ship SKIN
  6, // Ship
  87, // Fighter
  18, // Drone
  30, // Apparel
]);

const RAFFLE_STATUS = Object.freeze({
  CREATED: 1,
  INVENTORY_PENDING: 2,
  INVENTORY_RECEIVED: 3,
  TOKEN_PENDING: 4,
  TOKEN_RECEIVED: 5,
  RUNNING: 6,
  FINISHED_UNDELIVERED: 7,
  FINISHED_DELIVERED: 8,
  FINISHED_EXPIRED: 9,
});

module.exports = {
  FILETIME_TICKS_PER_MS,
  SEED_DURATION_MS,
  HISTORY_PAGE_SIZE,
  DEFAULT_GRAB_SIZE,
  DEFAULT_STARTUP_SEED_COUNT,
  MAX_QA_SEED_COUNT,
  SEED_OWNER_ID,
  SEED_ID_BASE,
  SEED_FALLBACK_STATION_ID,
  SEED_FALLBACK_SYSTEM_ID,
  SEED_FALLBACK_TYPE_ID,
  SEED_TICKET_COUNTS,
  SEED_TICKET_PRICES,
  SEED_PREFERRED_TYPE_IDS,
  SEED_FALLBACK_ITEM_TYPE_IDS,
  TOKEN_TYPE_ID,
  BROKERS_FEE,
  RAFFLE_TAX_PERCENTAGE,
  DEFAULT_PLEX_PRICE_OVERRIDE,
  TOKEN_PRICE_DIVISOR,
  MIN_TOTAL_PRICE,
  MAX_TOTAL_PRICE,
  TICKET_COUNT_POOL,
  PRIVATE_RESTRICTION_ID,
  RAFFLE_ESCROW_FLAG,
  SEEDED_TOKEN_STACK_SIZE,
  BLUEPRINT_TYPE,
  ALLOWED_CATEGORY_IDS,
  RAFFLE_STATUS,
};
