const MICHELLE_DIRECT_CRITICAL_ECHO_DESTINY_LEAD = 1;
const MICHELLE_HELD_FUTURE_DESTINY_LEAD = 2;
const MICHELLE_POST_HELD_FUTURE_DESTINY_LEAD =
  MICHELLE_HELD_FUTURE_DESTINY_LEAD + 1;

const MOVEMENT_MICHELLE_CONTRACT = Object.freeze({
  MICHELLE_DIRECT_CRITICAL_ECHO_DESTINY_LEAD,
  MICHELLE_HELD_FUTURE_DESTINY_LEAD,
  MICHELLE_POST_HELD_FUTURE_DESTINY_LEAD,
});

module.exports = {
  MOVEMENT_MICHELLE_CONTRACT,
  ...MOVEMENT_MICHELLE_CONTRACT,
};
