const path = require("path");

const {
  getIndustryActivityServiceIDs,
} = require(path.join(__dirname, "../structure/structureServiceAuthority"));

const INDUSTRY_ACTIVITY = Object.freeze({
  MANUFACTURING: 1,
  RESEARCH_TIME: 3,
  RESEARCH_MATERIAL: 4,
  COPYING: 5,
  INVENTION: 8,
  REACTION: 9,
});

const INDUSTRY_STATUS = Object.freeze({
  UNSUBMITTED: 0,
  INSTALLED: 1,
  PAUSED: 2,
  READY: 3,
  COMPLETED: 100,
  DELIVERED: 101,
  CANCELLED: 102,
  REVERTED: 103,
});

const INDUSTRY_ERROR = Object.freeze({
  INVALID_OWNER: 1,
  INVALID_CHARACTER: 2,
  INVALID_CORPORATION: 3,
  INVALID_RUNS: 4,
  INVALID_LICENSED_RUNS: 5,
  INVALID_INPUT_LOCATION: 6,
  INVALID_OUTPUT_LOCATION: 7,
  INVALID_PRODUCT: 8,
  INVALID_COST: 9,
  INVALID_ACTIVITY: 10,
  INVALID_FACILITY: 11,
  MISSING_ACTIVITY: 12,
  MISSING_ROLE: 13,
  MISSING_BLUEPRINT: 14,
  MISSING_FACILITY: 15,
  MISSING_MATERIAL: 16,
  MISSING_INPUT_LOCATION: 17,
  MISSING_OUTPUT_LOCATION: 18,
  ACCOUNT_FUNDS: 19,
  ACCOUNT_ACCESS: 20,
  INCOMPATIBLE_ACTIVITY: 21,
  BLUEPRINT_ACCESS: 22,
  BLUEPRINT_INSTALLED: 23,
  BLUEPRINT_WRONG_FACILITY: 24,
  MISMATCH_COST: 25,
  MISMATCH_TAX: 26,
  MISMATCH_TIME: 27,
  MISMATCH_MATERIAL: 28,
  INVALID_BLUEPRINT_LOCATION: 29,
  MISSING_SKILL: 30,
  SLOTS_FULL: 31,
  FACILITY_DISTANCE: 32,
  FACILITY_ACTIVITY: 33,
  FACILITY_TYPE: 34,
  RUN_LENGTH: 38,
  RESEARCH_LIMIT: 39,
  FACILITY_OFFLINE: 40,
  FACILITY_DENIED: 41,
  INPUT_ACCESS: 43,
  ACCOUNT_INVALID: 44,
  INVALID_MATERIAL_EFFICIENCY: 45,
  INVALID_TIME_EFFICIENCY: 46,
  OUTPUT_OVERFLOW: 47,
  STANDINGS_RESTRICTION: 48,
});

const INDUSTRY_ERROR_NAME = Object.freeze(
  Object.fromEntries(
    Object.entries(INDUSTRY_ERROR).map(([name, value]) => [value, name]),
  ),
);

const BLUEPRINT_LIMIT = 500;
const INDUSTRY_BLUEPRINT_TABLE = "industryBlueprints";
const INDUSTRY_FACILITY_TABLE = "industryFacilities";
const INDUSTRY_BLUEPRINT_STATE_TABLE = "industryBlueprintState";
const INDUSTRY_JOBS_TABLE = "industryJobs";
const INDUSTRY_RUNTIME_TABLE = "industryRuntime";
const INDUSTRY_FACILITY_STATE_TABLE = "industryFacilityState";
const BLUEPRINT_CATEGORY_ID = 9;
const INDUSTRY_INSTALLED_LOCATION_ID = 2003;
const ITEM_FLAG_HANGAR = 4;
const ITEM_FLAG_CORP_DELIVERIES = 62;
const ITEM_FLAG_CAPSULEER_DELIVERIES = 187;
const ITEM_FLAG_CORP_HANGAR_1 = 115;
const ITEM_FLAG_CORP_HANGAR_2 = 116;
const ITEM_FLAG_CORP_HANGAR_3 = 117;
const ITEM_FLAG_CORP_HANGAR_4 = 118;
const ITEM_FLAG_CORP_HANGAR_5 = 119;
const ITEM_FLAG_CORP_HANGAR_6 = 120;
const ITEM_FLAG_CORP_HANGAR_7 = 121;
const FACTORY_SERVICE_ID = 14;
const LABORATORY_SERVICE_ID = 15;
const DEFAULT_ACCOUNT_KEY = 1000;
const DEFAULT_TAX_RATE = 0.0;
const DEFAULT_SCC_TAX_MODIFIER = 1.0;
const COST_PERCENTAGE = 0.02;
const SCC_SURCHARGE_RATE = 0.04;
const SCC_SURCHARGE_RESEARCH_DISCOUNT_MODIFIER = 0.5;
const MATERIAL_ROUND_PRECISION = 2;
const MAX_MANUFACTURING_RUNS = 1000000;
const MAX_COPY_RUNS = 500;
const MAX_JOB_LENGTH_SECONDS = 2592000;
const MAX_MATERIAL_EFFICIENCY = 10;
const MAX_TIME_EFFICIENCY = 20;
const STEP_MATERIAL_EFFICIENCY = 1;
const STEP_TIME_EFFICIENCY = 2;
const RESEARCH_TIME_MULTIPLIERS = Object.freeze([
  1.0,
  29 / 21.0,
  23 / 7.0,
  39 / 5.0,
  278 / 15.0,
  928 / 21.0,
  2200 / 21.0,
  5251 / 21.0,
  4163 / 7.0,
  29660 / 21.0,
]);
const ROLE_FACTORY_MANAGER = 1024n;
const ROLE_FACTORY_MANUFACTURING = 1125899906842624n;
const ROLE_FACTORY_SCIENCE = 2251799813685248n;
const ROLE_HANGAR_TAKE_1 = 8192n;
const ROLE_HANGAR_TAKE_2 = 16384n;
const ROLE_HANGAR_TAKE_3 = 32768n;
const ROLE_HANGAR_TAKE_4 = 65536n;
const ROLE_HANGAR_TAKE_5 = 131072n;
const ROLE_HANGAR_TAKE_6 = 262144n;
const ROLE_HANGAR_TAKE_7 = 524288n;
const ROLE_HANGAR_QUERY_1 = 1048576n;
const ROLE_HANGAR_QUERY_2 = 2097152n;
const ROLE_HANGAR_QUERY_3 = 4194304n;
const ROLE_HANGAR_QUERY_4 = 8388608n;
const ROLE_HANGAR_QUERY_5 = 16777216n;
const ROLE_HANGAR_QUERY_6 = 33554432n;
const ROLE_HANGAR_QUERY_7 = 67108864n;
const ROLE_ACCOUNT_TAKE_1 = 134217728n;
const ROLE_ACCOUNT_TAKE_2 = 268435456n;
const ROLE_ACCOUNT_TAKE_3 = 536870912n;
const ROLE_ACCOUNT_TAKE_4 = 1073741824n;
const ROLE_ACCOUNT_TAKE_5 = 2147483648n;
const ROLE_ACCOUNT_TAKE_6 = 4294967296n;
const ROLE_ACCOUNT_TAKE_7 = 8589934592n;
const CORP_BLUEPRINT_VIEW_MASK =
  ROLE_FACTORY_MANAGER | ROLE_FACTORY_MANUFACTURING | ROLE_FACTORY_SCIENCE;
const CORP_HANGAR_FLAGS = Object.freeze([
  ITEM_FLAG_CORP_HANGAR_1,
  ITEM_FLAG_CORP_HANGAR_2,
  ITEM_FLAG_CORP_HANGAR_3,
  ITEM_FLAG_CORP_HANGAR_4,
  ITEM_FLAG_CORP_HANGAR_5,
  ITEM_FLAG_CORP_HANGAR_6,
  ITEM_FLAG_CORP_HANGAR_7,
]);
const CORP_HANGAR_QUERY_ROLE_BY_FLAG = Object.freeze({
  [ITEM_FLAG_CORP_HANGAR_1]: ROLE_HANGAR_QUERY_1,
  [ITEM_FLAG_CORP_HANGAR_2]: ROLE_HANGAR_QUERY_2,
  [ITEM_FLAG_CORP_HANGAR_3]: ROLE_HANGAR_QUERY_3,
  [ITEM_FLAG_CORP_HANGAR_4]: ROLE_HANGAR_QUERY_4,
  [ITEM_FLAG_CORP_HANGAR_5]: ROLE_HANGAR_QUERY_5,
  [ITEM_FLAG_CORP_HANGAR_6]: ROLE_HANGAR_QUERY_6,
  [ITEM_FLAG_CORP_HANGAR_7]: ROLE_HANGAR_QUERY_7,
});
const CORP_HANGAR_TAKE_ROLE_BY_FLAG = Object.freeze({
  [ITEM_FLAG_CORP_HANGAR_1]: ROLE_HANGAR_TAKE_1,
  [ITEM_FLAG_CORP_HANGAR_2]: ROLE_HANGAR_TAKE_2,
  [ITEM_FLAG_CORP_HANGAR_3]: ROLE_HANGAR_TAKE_3,
  [ITEM_FLAG_CORP_HANGAR_4]: ROLE_HANGAR_TAKE_4,
  [ITEM_FLAG_CORP_HANGAR_5]: ROLE_HANGAR_TAKE_5,
  [ITEM_FLAG_CORP_HANGAR_6]: ROLE_HANGAR_TAKE_6,
  [ITEM_FLAG_CORP_HANGAR_7]: ROLE_HANGAR_TAKE_7,
});
const CORP_WALLET_TAKE_ROLE_BY_KEY = Object.freeze({
  1000: ROLE_ACCOUNT_TAKE_1,
  1001: ROLE_ACCOUNT_TAKE_2,
  1002: ROLE_ACCOUNT_TAKE_3,
  1003: ROLE_ACCOUNT_TAKE_4,
  1004: ROLE_ACCOUNT_TAKE_5,
  1005: ROLE_ACCOUNT_TAKE_6,
  1006: ROLE_ACCOUNT_TAKE_7,
});
const FACILITY_RANGE_BY_SKILL_LEVEL = Object.freeze({
  0: 0,
  1: 5,
  2: 10,
  3: 15,
  4: 20,
  5: 25,
});
const MAX_INDUSTRY_DISTANCE = 25;
const DEFAULT_MONITOR_AVAILABLE_MATERIALS = Object.freeze({});
const INDUSTRY_REFERENCE = Object.freeze({
  BLUEPRINT: 1,
  DECRYPTOR: 3,
  SYSTEM: 4,
  FACILITY: 5,
  SKILLS: 6,
  DISTRICT: 8,
  FACTION: 9,
  CLONE_STATE: 10,
  RIG: 11,
  HULL: 12,
});
const GM_BP_PRESETS = Object.freeze({
  frigate: "Rifter",
  destroyer: "Cormorant",
  cruiser: "Caracal",
  ammo: "Scourge Light Missile",
  lightdrones: "Hobgoblin I",
  module: "200mm AutoCannon I",
  rigs: "Small Core Defense Field Extender I",
  components: "Capital Armor Plates",
  capitalcomponents: "Capital Armor Plates",
});
const DEMO_RUN_COUNT = Object.freeze({
  frigate: 1,
  destroyer: 1,
  cruiser: 1,
  ammo: 100,
  lightdrones: 5,
  module: 5,
  rigs: 5,
  components: 2,
  capitalcomponents: 2,
});
const FACILITY_ACTIVITY_SERVICE_IDS = Object.freeze({
  [INDUSTRY_ACTIVITY.MANUFACTURING]: new Set(
    getIndustryActivityServiceIDs(INDUSTRY_ACTIVITY.MANUFACTURING, INDUSTRY_ACTIVITY),
  ),
  [INDUSTRY_ACTIVITY.RESEARCH_TIME]: new Set(
    getIndustryActivityServiceIDs(INDUSTRY_ACTIVITY.RESEARCH_TIME, INDUSTRY_ACTIVITY),
  ),
  [INDUSTRY_ACTIVITY.RESEARCH_MATERIAL]: new Set(
    getIndustryActivityServiceIDs(INDUSTRY_ACTIVITY.RESEARCH_MATERIAL, INDUSTRY_ACTIVITY),
  ),
  [INDUSTRY_ACTIVITY.COPYING]: new Set(
    getIndustryActivityServiceIDs(INDUSTRY_ACTIVITY.COPYING, INDUSTRY_ACTIVITY),
  ),
  [INDUSTRY_ACTIVITY.INVENTION]: new Set(
    getIndustryActivityServiceIDs(INDUSTRY_ACTIVITY.INVENTION, INDUSTRY_ACTIVITY),
  ),
  [INDUSTRY_ACTIVITY.REACTION]: new Set(
    getIndustryActivityServiceIDs(INDUSTRY_ACTIVITY.REACTION, INDUSTRY_ACTIVITY),
  ),
});

module.exports = {
  INDUSTRY_ACTIVITY,
  INDUSTRY_STATUS,
  INDUSTRY_ERROR,
  INDUSTRY_ERROR_NAME,
  BLUEPRINT_LIMIT,
  INDUSTRY_BLUEPRINT_TABLE,
  INDUSTRY_FACILITY_TABLE,
  INDUSTRY_BLUEPRINT_STATE_TABLE,
  INDUSTRY_JOBS_TABLE,
  INDUSTRY_RUNTIME_TABLE,
  INDUSTRY_FACILITY_STATE_TABLE,
  BLUEPRINT_CATEGORY_ID,
  INDUSTRY_INSTALLED_LOCATION_ID,
  ITEM_FLAG_HANGAR,
  ITEM_FLAG_CORP_DELIVERIES,
  ITEM_FLAG_CAPSULEER_DELIVERIES,
  ITEM_FLAG_CORP_HANGAR_1,
  ITEM_FLAG_CORP_HANGAR_2,
  ITEM_FLAG_CORP_HANGAR_3,
  ITEM_FLAG_CORP_HANGAR_4,
  ITEM_FLAG_CORP_HANGAR_5,
  ITEM_FLAG_CORP_HANGAR_6,
  ITEM_FLAG_CORP_HANGAR_7,
  FACTORY_SERVICE_ID,
  LABORATORY_SERVICE_ID,
  DEFAULT_ACCOUNT_KEY,
  DEFAULT_TAX_RATE,
  DEFAULT_SCC_TAX_MODIFIER,
  COST_PERCENTAGE,
  SCC_SURCHARGE_RATE,
  SCC_SURCHARGE_RESEARCH_DISCOUNT_MODIFIER,
  MATERIAL_ROUND_PRECISION,
  MAX_MANUFACTURING_RUNS,
  MAX_COPY_RUNS,
  MAX_JOB_LENGTH_SECONDS,
  MAX_MATERIAL_EFFICIENCY,
  MAX_TIME_EFFICIENCY,
  STEP_MATERIAL_EFFICIENCY,
  STEP_TIME_EFFICIENCY,
  RESEARCH_TIME_MULTIPLIERS,
  ROLE_FACTORY_MANAGER,
  ROLE_FACTORY_MANUFACTURING,
  ROLE_FACTORY_SCIENCE,
  CORP_BLUEPRINT_VIEW_MASK,
  CORP_HANGAR_FLAGS,
  CORP_HANGAR_QUERY_ROLE_BY_FLAG,
  CORP_HANGAR_TAKE_ROLE_BY_FLAG,
  CORP_WALLET_TAKE_ROLE_BY_KEY,
  FACILITY_RANGE_BY_SKILL_LEVEL,
  MAX_INDUSTRY_DISTANCE,
  DEFAULT_MONITOR_AVAILABLE_MATERIALS,
  INDUSTRY_REFERENCE,
  GM_BP_PRESETS,
  DEMO_RUN_COUNT,
  FACILITY_ACTIVITY_SERVICE_IDS,
};
